import { Project } from './types';

export const initialProjects: Project[] = [
  {
    id: 1,
    name: 'Piano House',
    imageUrl: 'https://github.com/humonoid-errr/umair.archviz/tree/main/portfolio/Piano%20house',
    theme: 'dark',
    galleryImages: [
      // Landscape
      'https://raw.githubusercontent.com/humonoid-errr/umair.archviz/refs/heads/main/portfolio/Piano%20house/1.jpg',
      'https://raw.githubusercontent.com/humonoid-errr/umair.archviz/refs/heads/main/portfolio/Piano%20house/2.jpg',
      'https://raw.githubusercontent.com/humonoid-errr/umair.archviz/refs/heads/main/portfolio/Piano%20house/3.jpg',
      'https://raw.githubusercontent.com/humonoid-errr/umair.archviz/refs/heads/main/portfolio/Piano%20house/4.jpg',
      'https://raw.githubusercontent.com/humonoid-errr/umair.archviz/refs/heads/main/portfolio/Piano%20house/5.jpg',
      'https://raw.githubusercontent.com/humonoid-errr/umair.archviz/refs/heads/main/portfolio/Piano%20house/6.jpg',
      'https://raw.githubusercontent.com/humonoid-errr/umair.archviz/refs/heads/main/portfolio/Piano%20house/7.jpg',
      'https://raw.githubusercontent.com/humonoid-errr/umair.archviz/refs/heads/main/portfolio/Piano%20house/8.jpg',
      'https://raw.githubusercontent.com/humonoid-errr/umair.archviz/refs/heads/main/portfolio/Piano%20house/9.jpg',
      // Portrait
      'https://raw.githubusercontent.com/humonoid-errr/umair.archviz/refs/heads/main/portfolio/Piano%20house/10.jpg',
      'https://raw.githubusercontent.com/humonoid-errr/umair.archviz/refs/heads/main/portfolio/Piano%20house/11.jpg',
      'https://raw.githubusercontent.com/humonoid-errr/umair.archviz/refs/heads/main/portfolio/Piano%20house/12.jpg',
      'https://raw.githubusercontent.com/humonoid-errr/umair.archviz/refs/heads/main/portfolio/Piano%20house/13.jpg',
      'https://raw.githubusercontent.com/humonoid-errr/umair.archviz/refs/heads/main/portfolio/Piano%20house/14.jpg',
      'https://raw.githubusercontent.com/humonoid-errr/umair.archviz/refs/heads/main/portfolio/Piano%20house/15.jpg',
    ],
  },
  {
    id: 2,
    name: 'Mountain Cabin',
    imageUrl: 'https://github.com/humonoid-errr/umair.archviz/tree/main/portfolio/Mountain%20Cabin',
    theme: 'dark',
    galleryImages: [
      'https://raw.githubusercontent.com/humonoid-errr/umair.archviz/refs/heads/main/portfolio/Mountain%20Cabin/1.jpg',
      'https://raw.githubusercontent.com/humonoid-errr/umair.archviz/refs/heads/main/portfolio/Mountain%20Cabin/2.jpg',
      'https://raw.githubusercontent.com/humonoid-errr/umair.archviz/refs/heads/main/portfolio/Mountain%20Cabin/3.jpg',
      'https://raw.githubusercontent.com/humonoid-errr/umair.archviz/refs/heads/main/portfolio/Mountain%20Cabin/4.jpg',
      'https://raw.githubusercontent.com/humonoid-errr/umair.archviz/refs/heads/main/portfolio/Mountain%20Cabin/5.jpg',
      'https://raw.githubusercontent.com/humonoid-errr/umair.archviz/refs/heads/main/portfolio/Mountain%20Cabin/6.jpg',
      'https://raw.githubusercontent.com/humonoid-errr/umair.archviz/refs/heads/main/portfolio/Mountain%20Cabin/7.jpg',
      'https://raw.githubusercontent.com/humonoid-errr/umair.archviz/refs/heads/main/portfolio/Mountain%20Cabin/8.jpg',
      'https://raw.githubusercontent.com/humonoid-errr/umair.archviz/refs/heads/main/portfolio/Mountain%20Cabin/9.jpg',
      'https://raw.githubusercontent.com/humonoid-errr/umair.archviz/refs/heads/main/portfolio/Mountain%20Cabin/10.jpg',
      'https://raw.githubusercontent.com/humonoid-errr/umair.archviz/refs/heads/main/portfolio/Mountain%20Cabin/11.jpg',
      'https://raw.githubusercontent.com/humonoid-errr/umair.archviz/refs/heads/main/portfolio/Mountain%20Cabin/12.jpg',
    ],
  },
  {
    id: 3,
    name: 'Alpine Villa',
    imageUrl: 'https://github.com/humonoid-errr/umair.archviz/tree/main/portfolio/Alpine%20Villa',
    theme: 'dark',
    galleryImages: [
      'https://raw.githubusercontent.com/humonoid-errr/umair.archviz/refs/heads/main/portfolio/Alpine%20Villa/1.jpg',
      'https://raw.githubusercontent.com/humonoid-errr/umair.archviz/refs/heads/main/portfolio/Alpine%20Villa/2.jpg',
      'https://raw.githubusercontent.com/humonoid-errr/umair.archviz/refs/heads/main/portfolio/Alpine%20Villa/3.jpg',
      'https://raw.githubusercontent.com/humonoid-errr/umair.archviz/refs/heads/main/portfolio/Alpine%20Villa/4.jpg',
      'https://raw.githubusercontent.com/humonoid-errr/umair.archviz/refs/heads/main/portfolio/Alpine%20Villa/5.jpg',
      'https://raw.githubusercontent.com/humonoid-errr/umair.archviz/refs/heads/main/portfolio/Alpine%20Villa/6.jpg',
      'https://raw.githubusercontent.com/humonoid-errr/umair.archviz/refs/heads/main/portfolio/Alpine%20Villa/7.jpg',
      'https://raw.githubusercontent.com/humonoid-errr/umair.archviz/refs/heads/main/portfolio/Alpine%20Villa/8.jpg',
      'https://raw.githubusercontent.com/humonoid-errr/umair.archviz/refs/heads/main/portfolio/Alpine%20Villa/9.jpg',
    ],
  },
  {
    id: 4,
    name: 'The Glass House',
    imageUrl: 'https://images.unsplash.com/photo-1537726235470-8504e3b77c06?q=80&w=1974&auto=format&fit=crop',
    theme: 'dark',
    galleryImages: [
      'https://images.unsplash.com/photo-1613490493576-7fde63acd811?q=80&w=2071&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1604014237800-1c9102c219da?q=80&w=2070&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1593902819383-299881373585?q=80&w=2070&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1558036117-15d82a90b9b1?q=80&w=2070&auto=format&fit=crop',
    ],
  },
  {
    id: 5,
    name: 'Bali Villa',
    imageUrl: 'https://images.unsplash.com/photo-1585544733989-12a964f4b826?q=80&w=2070&auto=format&fit=crop',
    theme: 'light',
    galleryImages: [
      'https://images.unsplash.com/photo-1596394516093-501ba68a0ba6?q=80&w=2070&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1561501900-3701fa6a0864?q=80&w=2070&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1610641818989-c2051b5e2cfd?q=80&w=2070&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1537996194471-e657df975ab4?q=80&w=1938&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1571888229994-77e8a4a28795?q=80&w=2074&auto=format&fit=crop',
    ],
  },
  {
    id: 6,
    name: 'Neoclassical Elevation',
    imageUrl: 'https://github.com/humonoid-errr/umair.archviz/tree/main/portfolio/neo%20classical',
    theme: 'light',
    galleryImages: [
      'https://raw.githubusercontent.com/humonoid-errr/umair.archviz/refs/heads/main/portfolio/neo%20classical/1.jpg',
    ],
  },
  {
    id: 7,
    name: 'Modern Minimalist Elevation',
    imageUrl: 'https://github.com/humonoid-errr/umair.archviz/tree/main/portfolio/modern%20minimilist',
    theme: 'dark',
    galleryImages: [
      'https://raw.githubusercontent.com/humonoid-errr/umair.archviz/refs/heads/main/portfolio/modern%20minimilist/1.jpg',
      'https://raw.githubusercontent.com/humonoid-errr/umair.archviz/refs/heads/main/portfolio/modern%20minimilist/2.jpg',
      'https://raw.githubusercontent.com/humonoid-errr/umair.archviz/refs/heads/main/portfolio/modern%20minimilist/3.jpg',
    ],
  },
];
