import { Project } from './types';

export const initialProjects: Project[] = [
  {
    id: 1,
    name: 'Piano House',
    imageUrl: 'https://cdn.jsdelivr.net/gh/humonoid-errr/umair.archviz@main/portfolio/Piano%20house/1.jpg',
    theme: 'dark',
    galleryImages: [
      'https://cdn.jsdelivr.net/gh/humonoid-errr/umair.archviz@main/portfolio/Piano%20house/1.jpg',
      'https://cdn.jsdelivr.net/gh/humonoid-errr/umair.archviz@main/portfolio/Piano%20house/2.jpg',
      'https://cdn.jsdelivr.net/gh/humonoid-errr/umair.archviz@main/portfolio/Piano%20house/3.jpg',
      'https://cdn.jsdelivr.net/gh/humonoid-errr/umair.archviz@main/portfolio/Piano%20house/4.jpg',
      'https://cdn.jsdelivr.net/gh/humonoid-errr/umair.archviz@main/portfolio/Piano%20house/5.jpg',
      'https://cdn.jsdelivr.net/gh/humonoid-errr/umair.archviz@main/portfolio/Piano%20house/6.jpg',
      'https://cdn.jsdelivr.net/gh/humonoid-errr/umair.archviz@main/portfolio/Piano%20house/7.jpg',
      'https://cdn.jsdelivr.net/gh/humonoid-errr/umair.archviz@main/portfolio/Piano%20house/8.jpg',
      'https://cdn.jsdelivr.net/gh/humonoid-errr/umair.archviz@main/portfolio/Piano%20house/9.jpg',
      'https://cdn.jsdelivr.net/gh/humonoid-errr/umair.archviz@main/portfolio/Piano%20house/10.jpg',
      'https://cdn.jsdelivr.net/gh/humonoid-errr/umair.archviz@main/portfolio/Piano%20house/11.jpg',
      'https://cdn.jsdelivr.net/gh/humonoid-errr/umair.archviz@main/portfolio/Piano%20house/12.jpg',
      'https://cdn.jsdelivr.net/gh/humonoid-errr/umair.archviz@main/portfolio/Piano%20house/13.jpg',
      'https://cdn.jsdelivr.net/gh/humonoid-errr/umair.archviz@main/portfolio/Piano%20house/14.jpg',
      'https://cdn.jsdelivr.net/gh/humonoid-errr/umair.archviz@main/portfolio/Piano%20house/15.jpg',
    ],
  },
  {
    id: 11,
    name: 'AlWijha Real Estate - Muscat Office',
    imageUrl: 'https://cdn.jsdelivr.net/gh/humonoid-errr/umair.archviz@main/portfolio/AlWijha%20Real%20Estate%20-%20Muscat%20Office%20Building%20New%20Changes/01%20-%20FRONT.jpg',
    theme: 'dark',
    galleryImages: [
      'https://cdn.jsdelivr.net/gh/humonoid-errr/umair.archviz@main/portfolio/AlWijha%20Real%20Estate%20-%20Muscat%20Office%20Building%20New%20Changes/01%20-%20FRONT.jpg',
      'https://cdn.jsdelivr.net/gh/humonoid-errr/umair.archviz@main/portfolio/AlWijha%20Real%20Estate%20-%20Muscat%20Office%20Building%20New%20Changes/02%20-%20LEFT.jpg',
      'https://cdn.jsdelivr.net/gh/humonoid-errr/umair.archviz@main/portfolio/AlWijha%20Real%20Estate%20-%20Muscat%20Office%20Building%20New%20Changes/05%20-%20LEFT%20-3.jpg',
      'https://cdn.jsdelivr.net/gh/humonoid-errr/umair.archviz@main/portfolio/AlWijha%20Real%20Estate%20-%20Muscat%20Office%20Building%20New%20Changes/07%20-%20LEFT%20-%206.jpg',
      'https://cdn.jsdelivr.net/gh/humonoid-errr/umair.archviz@main/portfolio/AlWijha%20Real%20Estate%20-%20Muscat%20Office%20Building%20New%20Changes/09%20-%20AERIAL.jpg',
      'https://cdn.jsdelivr.net/gh/humonoid-errr/umair.archviz@main/portfolio/AlWijha%20Real%20Estate%20-%20Muscat%20Office%20Building%20New%20Changes/11%20-%20PARKING.jpg',
      'https://cdn.jsdelivr.net/gh/humonoid-errr/umair.archviz@main/portfolio/AlWijha%20Real%20Estate%20-%20Muscat%20Office%20Building%20New%20Changes/13%20-%20STAIRS.jpg',
    ],
  },
  {
    id: 12,
    name: 'Noor Al Layl Villa',
    imageUrl: 'https://cdn.jsdelivr.net/gh/humonoid-errr/umair.archviz@main/portfolio/Noor%20Al%20Layl%20Villa/1.1.jpg',
    theme: 'dark',
    galleryImages: [
      'https://cdn.jsdelivr.net/gh/humonoid-errr/umair.archviz@main/portfolio/Noor%20Al%20Layl%20Villa/1.1.jpg',
      'https://cdn.jsdelivr.net/gh/humonoid-errr/umair.archviz@main/portfolio/Noor%20Al%20Layl%20Villa/2.2.jpg',
      'https://cdn.jsdelivr.net/gh/humonoid-errr/umair.archviz@main/portfolio/Noor%20Al%20Layl%20Villa/3.3.jpg',
      'https://cdn.jsdelivr.net/gh/humonoid-errr/umair.archviz@main/portfolio/Noor%20Al%20Layl%20Villa/4.4.jpg',
      'https://cdn.jsdelivr.net/gh/humonoid-errr/umair.archviz@main/portfolio/Noor%20Al%20Layl%20Villa/5.5.jpg',
    ],
  },
  {
    id: 2,
    name: 'Mountain Cabin',
    imageUrl: 'https://cdn.jsdelivr.net/gh/humonoid-errr/umair.archviz@main/portfolio/Mountain%20Cabin/1.jpg',
    theme: 'dark',
    galleryImages: [
      'https://cdn.jsdelivr.net/gh/humonoid-errr/umair.archviz@main/portfolio/Mountain%20Cabin/1.jpg',
      'https://cdn.jsdelivr.net/gh/humonoid-errr/umair.archviz@main/portfolio/Mountain%20Cabin/2.jpg',
      'https://cdn.jsdelivr.net/gh/humonoid-errr/umair.archviz@main/portfolio/Mountain%20Cabin/3.jpg',
      'https://cdn.jsdelivr.net/gh/humonoid-errr/umair.archviz@main/portfolio/Mountain%20Cabin/4.jpg',
      'https://cdn.jsdelivr.net/gh/humonoid-errr/umair.archviz@main/portfolio/Mountain%20Cabin/5.jpg',
      'https://cdn.jsdelivr.net/gh/humonoid-errr/umair.archviz@main/portfolio/Mountain%20Cabin/7.jpg',
      'https://cdn.jsdelivr.net/gh/humonoid-errr/umair.archviz@main/portfolio/Mountain%20Cabin/8.jpg',
      'https://cdn.jsdelivr.net/gh/humonoid-errr/umair.archviz@main/portfolio/Mountain%20Cabin/9.jpg',
      'https://cdn.jsdelivr.net/gh/humonoid-errr/umair.archviz@main/portfolio/Mountain%20Cabin/10.jpg',
      'https://cdn.jsdelivr.net/gh/humonoid-errr/umair.archviz@main/portfolio/Mountain%20Cabin/11.jpg',
      'https://cdn.jsdelivr.net/gh/humonoid-errr/umair.archviz@main/portfolio/Mountain%20Cabin/12.jpg',
    ],
  },
  {
    id: 3,
    name: 'Alpine Villa',
    imageUrl: 'https://cdn.jsdelivr.net/gh/humonoid-errr/umair.archviz@main/portfolio/Alpine%20Villa/1.jpg',
    theme: 'dark',
    galleryImages: [
      'https://cdn.jsdelivr.net/gh/humonoid-errr/umair.archviz@main/portfolio/Alpine%20Villa/1.jpg',
      'https://cdn.jsdelivr.net/gh/humonoid-errr/umair.archviz@main/portfolio/Alpine%20Villa/2.jpg',
      'https://cdn.jsdelivr.net/gh/humonoid-errr/umair.archviz@main/portfolio/Alpine%20Villa/3.jpg',
      'https://cdn.jsdelivr.net/gh/humonoid-errr/umair.archviz@main/portfolio/Alpine%20Villa/4.jpg',
      'https://cdn.jsdelivr.net/gh/humonoid-errr/umair.archviz@main/portfolio/Alpine%20Villa/5.jpg',
      'https://cdn.jsdelivr.net/gh/humonoid-errr/umair.archviz@main/portfolio/Alpine%20Villa/6.jpg',
      'https://cdn.jsdelivr.net/gh/humonoid-errr/umair.archviz@main/portfolio/Alpine%20Villa/7.jpg',
      'https://cdn.jsdelivr.net/gh/humonoid-errr/umair.archviz@main/portfolio/Alpine%20Villa/8.jpg',
      'https://cdn.jsdelivr.net/gh/humonoid-errr/umair.archviz@main/portfolio/Alpine%20Villa/9.jpg',
    ],
  },
  {
    id: 9,
    name: 'Apartment Sanskar',
    imageUrl: 'https://cdn.jsdelivr.net/gh/humonoid-errr/umair.archviz@main/portfolio/apartment%20sanskar/1.jpg',
    theme: 'light',
    is360: true,
    galleryImages: [
      'https://cdn.jsdelivr.net/gh/humonoid-errr/umair.archviz@main/portfolio/apartment%20sanskar/1.jpg',
      'https://cdn.jsdelivr.net/gh/humonoid-errr/umair.archviz@main/portfolio/apartment%20sanskar/2.jpg',
      'https://cdn.jsdelivr.net/gh/humonoid-errr/umair.archviz@main/portfolio/apartment%20sanskar/3.jpg',
      'https://cdn.jsdelivr.net/gh/humonoid-errr/umair.archviz@main/portfolio/apartment%20sanskar/4-4.jpg',
      'https://cdn.jsdelivr.net/gh/humonoid-errr/umair.archviz@main/portfolio/apartment%20sanskar/5.jpg',
      'https://cdn.jsdelivr.net/gh/humonoid-errr/umair.archviz@main/portfolio/apartment%20sanskar/6.jpg',
      'https://cdn.jsdelivr.net/gh/humonoid-errr/umair.archviz@main/portfolio/apartment%20sanskar/7.jpg',
    ],
  },
  {
    id: 10,
    name: 'Babita Apartment',
    imageUrl: 'https://cdn.jsdelivr.net/gh/humonoid-errr/umair.archviz@main/portfolio/Babita%20Apartment',
    theme: 'light',
    is360: true,
    galleryImages: [
      'https://cdn.jsdelivr.net/gh/humonoid-errr/umair.archviz@main/portfolio/Babita%20Apartment/1.jpg',
      'https://cdn.jsdelivr.net/gh/humonoid-errr/umair.archviz@main/portfolio/Babita%20Apartment/2.jpg',
      'https://cdn.jsdelivr.net/gh/humonoid-errr/umair.archviz@main/portfolio/Babita%20Apartment/3.jpg',
      'https://cdn.jsdelivr.net/gh/humonoid-errr/umair.archviz@main/portfolio/Babita%20Apartment/4.jpg',
    ],
  },
  {
    id: 4,
    name: 'The Glass House',
    imageUrl: 'https://cdn.jsdelivr.net/gh/humonoid-errr/umair.archviz@main/portfolio/glass%20house/1.jpg',
    theme: 'dark',
    galleryImages: [
      'https://cdn.jsdelivr.net/gh/humonoid-errr/umair.archviz@main/portfolio/glass%20house/1.jpg',
      'https://cdn.jsdelivr.net/gh/humonoid-errr/umair.archviz@main/portfolio/glass%20house/2.jpg',
      'https://cdn.jsdelivr.net/gh/humonoid-errr/umair.archviz@main/portfolio/glass%20house/3.jpg',
      'https://cdn.jsdelivr.net/gh/humonoid-errr/umair.archviz@main/portfolio/glass%20house/4.jpg',
      'https://cdn.jsdelivr.net/gh/humonoid-errr/umair.archviz@main/portfolio/glass%20house/5.jpg',
      'https://cdn.jsdelivr.net/gh/humonoid-errr/umair.archviz@main/portfolio/glass%20house/6.jpg',
      'https://cdn.jsdelivr.net/gh/humonoid-errr/umair.archviz@main/portfolio/glass%20house/7.jpg',
      'https://cdn.jsdelivr.net/gh/humonoid-errr/umair.archviz@main/portfolio/glass%20house/8.jpg',
      'https://cdn.jsdelivr.net/gh/humonoid-errr/umair.archviz@main/portfolio/glass%20house/9.jpg',
      'https://cdn.jsdelivr.net/gh/humonoid-errr/umair.archviz@main/portfolio/glass%20house/10.jpg',
      'https://cdn.jsdelivr.net/gh/humonoid-errr/umair.archviz@main/portfolio/glass%20house/11.jpg',
      'https://cdn.jsdelivr.net/gh/humonoid-errr/umair.archviz@main/portfolio/glass%20house/12.jpg',
      'https://cdn.jsdelivr.net/gh/humonoid-errr/umair.archviz@main/portfolio/glass%20house/13.jpg',
    ],
  },
  {
    id: 5,
    name: 'Bali Villa',
    imageUrl: 'https://cdn.jsdelivr.net/gh/humonoid-errr/umair.archviz@main/portfolio/bali%20villa/1.jpg',
    theme: 'light',
    galleryImages: [
      'https://cdn.jsdelivr.net/gh/humonoid-errr/umair.archviz@main/portfolio/bali%20villa/1.jpg',
      'https://cdn.jsdelivr.net/gh/humonoid-errr/umair.archviz@main/portfolio/bali%20villa/2.jpg',
      'https://cdn.jsdelivr.net/gh/humonoid-errr/umair.archviz@main/portfolio/bali%20villa/3.jpg',
      'https://cdn.jsdelivr.net/gh/humonoid-errr/umair.archviz@main/portfolio/bali%20villa/4.jpg',
      'https://cdn.jsdelivr.net/gh/humonoid-errr/umair.archviz@main/portfolio/bali%20villa/5.jpg',
      'https://cdn.jsdelivr.net/gh/humonoid-errr/umair.archviz@main/portfolio/bali%20villa/6.jpg',
      'https://cdn.jsdelivr.net/gh/humonoid-errr/umair.archviz@main/portfolio/bali%20villa/7.jpg',
    ],
  },
  {
    id: 6,
    name: 'Neoclassical Elevation',
    imageUrl: 'https://cdn.jsdelivr.net/gh/humonoid-errr/umair.archviz@main/portfolio/neo%20classical/1.jpg',
    theme: 'light',
    galleryImages: [
      'https://cdn.jsdelivr.net/gh/humonoid-errr/umair.archviz@main/portfolio/neo%20classical/1.jpg',
      'https://cdn.jsdelivr.net/gh/humonoid-errr/umair.archviz@main/portfolio/neo%20classical/2.jpg',
    ],
  },
  {
    id: 7,
    name: 'Modern Minimalist Elevation',
    imageUrl: 'https://cdn.jsdelivr.net/gh/humonoid-errr/umair.archviz@main/portfolio/modern%20minimilist/1.jpg',
    theme: 'dark',
    galleryImages: [
      'https://cdn.jsdelivr.net/gh/humonoid-errr/umair.archviz@main/portfolio/modern%20minimilist/1.jpg',
      'https://cdn.jsdelivr.net/gh/humonoid-errr/umair.archviz@main/portfolio/modern%20minimilist/2.jpg',
      'https://cdn.jsdelivr.net/gh/humonoid-errr/umair.archviz@main/portfolio/modern%20minimilist/3.jpg',
      'https://cdn.jsdelivr.net/gh/humonoid-errr/umair.archviz@main/portfolio/modern%20minimilist/4.jpg',
      'https://cdn.jsdelivr.net/gh/humonoid-errr/umair.archviz@main/portfolio/modern%20minimilist/5.jpg',
    ],
  },
];